name: End-to-End Test
on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  unit:
    name: Cypress
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Current Branch
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Set NPM Production Configuration to false
        run: npm config set -g production false

      - name: Remove existing package-lock to support multiple platforms
        run: npm run rm-package-lock

      - name: Install All Dependencies
        run: yarn install --link-duplicates

      - name: Build Motif Bundle
        working-directory: './packages/motif'
        run: npm run build

      - name: Build Demo Bundles
        working-directory: './packages/motif-demo'
        run: npm run build

      - name: Setup kernel for React, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Cypress run
        uses: cypress-io/github-action@v2
        timeout-minutes: 30
        with:
          install: false
          start: npm run demo:serve
          command: npm run cypress
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 100
