name: End-to-End Test
on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  unit:
    name: Cypress
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Current Branch
        uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install NPM Dependencies
        run: npm run bootstrap

      - name: Setup kernel for React, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: 'npm run demo'
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
