name: Unit Test
on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  unit:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Current Branch
        uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Set NPM Production Configuration to false
        run: npm config set -g production false

      - name: Remove existing package-lock to support multiple platforms
        run: npm run rm-package-lock

      - name: Install multiple packages' dependencies
        run: npm run bootstrap

      - name: Run Unit Test
        run: ls -al node_modules/
