name: Unit Test
on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  unit:
    name: Jest
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    steps:
      - name: Checkout to Current Branch
        uses: actions/checkout@v2

      - name: Use Node.js 15
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Set NPM Production Configuration to false
        run: npm config set -g production false

      - name: Remove existing package-lock to support multiple platforms
        run: npm run rm-package-lock

      # - name: Install Development Dependencies
      #   working-directory: './packages/motif'
      #   run: npm install --include=dev --legacy-peer-deps

      - name: Install Dependencies
        working-directory: './packages/motif'
        run: npm install --legacy-peer-deps

      - name: Run Unit Test
        working-directory: './packages/motif'
        run: npm run test
