name: Unit Test
on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  unit:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Current Branch
        uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install root NPM dependencies
        run: npm install

      - name: Install multiple packages' dependencies
        run: npm run bootstrap

      - name: Run Unit Test
        working-directory: './packages/motif'
        run: npm run test
